import { AlertTriangle, BookOpenCheck, ClipboardList, PlusCircle, ShieldCheck } from "lucide-react";
import { useState, type FormEvent } from "react";
import DashboardLayout from "@/components/DashboardLayout";
import { inr } from "@/components/foundation/FinancialSummary";
import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";

export default function AdminOperations() {
  const { user, loading } = useAuth();
  return <DashboardLayout>{loading ? null : user?.role !== "admin" ? <AccessDenied /> : <Operations />}</DashboardLayout>;
}

function AccessDenied() { return <div className="mx-auto max-w-xl rounded-xl border border-[#efd0cb] bg-[#fff4f2] p-7"><div className="flex gap-3"><AlertTriangle className="h-5 w-5 text-[#c94a45]" /><div><h1 className="display-title text-3xl">Admin access is required.</h1><p className="mt-2 leading-7 text-[#6d4743]">Financial operations are restricted to approved administrators. The server independently verifies this role for every mutation.</p></div></div></div>; }

function Operations() {
  const utils = trpc.useUtils();
  const dashboard = trpc.admin.dashboard.useQuery(); const members = trpc.admin.members.useQuery(); const donations = trpc.admin.donationLedger.useQuery({ limit: 10 }); const expenses = trpc.admin.expenseLedger.useQuery({ limit: 10 });
  const offlineDonation = trpc.admin.recordOfflineDonation.useMutation({ onSuccess: () => { utils.admin.dashboard.invalidate(); utils.admin.donationLedger.invalidate(); } });
  const expense = trpc.admin.recordExpense.useMutation({ onSuccess: () => { utils.admin.dashboard.invalidate(); utils.admin.expenseLedger.invalidate(); } });
  const [memberId, setMemberId] = useState(""); const [donationAmount, setDonationAmount] = useState(""); const [paymentMode, setPaymentMode] = useState<"cash" | "cheque">("cash"); const [donationDate, setDonationDate] = useState(new Date().toISOString().slice(0, 10));
  const [expenseAmount, setExpenseAmount] = useState(""); const [category, setCategory] = useState<"coaching" | "library" | "kanyadan" | "operations" | "other">("operations"); const [description, setDescription] = useState(""); const [expenseDate, setExpenseDate] = useState(new Date().toISOString().slice(0, 10));
  const submitDonation = (event: FormEvent) => { event.preventDefault(); const paise = Math.round(Number(donationAmount) * 100); if (!memberId || !Number.isFinite(paise) || paise <= 0) return; offlineDonation.mutate({ memberId: Number(memberId), amountPaise: paise, paymentMode, receivedAt: new Date(`${donationDate}T12:00:00`), idempotencyKey: crypto.randomUUID() }, { onSuccess: () => { setDonationAmount(""); setMemberId(""); } }); };
  const submitExpense = (event: FormEvent) => { event.preventDefault(); const paise = Math.round(Number(expenseAmount) * 100); if (!Number.isFinite(paise) || paise <= 0 || description.trim().length < 3) return; expense.mutate({ amountPaise: paise, category, publicDescription: description.trim(), spentAt: new Date(`${expenseDate}T12:00:00`) }, { onSuccess: () => { setExpenseAmount(""); setDescription(""); } }); };
  const summary = dashboard.data?.summary;
  return <div className="mx-auto max-w-6xl space-y-6"><div className="flex flex-col gap-3 border-b border-[#e5dcc7] pb-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="section-kicker">Protected financial operations</p><h1 className="display-title mt-1 text-4xl text-[#28306b]">Record the work. Preserve the trail.</h1><p className="mt-2 max-w-2xl text-[#635f58]">Each successful mutation writes an audit event. Amounts are stored as paise and public transparency derives from source ledger rows.</p></div><div className="inline-flex items-center gap-2 rounded-full bg-[#eef8f4] px-3 py-2 text-sm font-bold text-[#18765d]"><ShieldCheck className="h-4 w-4" /> Admin session verified</div></div>
    <div className="grid gap-3 sm:grid-cols-3"><Metric label="Raised" value={summary ? inr(summary.totalRaisedPaise) : "—"} /><Metric label="Spent" value={summary ? inr(summary.totalSpentPaise) : "—"} /><Metric label="Available" value={summary ? inr(summary.balancePaise) : "—"} /></div>
    <div className="grid gap-6 xl:grid-cols-2"><form className="rounded-xl border border-[#e5dcc7] bg-[#fffdf6] p-6" onSubmit={submitDonation}><div className="flex items-start gap-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-[#e8effc] text-[#28306b]"><PlusCircle className="h-5 w-5" /></span><div><p className="section-kicker">Offline donation</p><h2 className="display-title text-2xl">Record cash or cheque</h2></div></div><p className="mt-3 text-sm leading-6 text-[#746f66]">A registered Member is required. Public anonymity changes display only, never this internal financial link.</p><div className="mt-5 grid gap-4"><Field label="Registered Member"><Select value={memberId} onValueChange={setMemberId} disabled={!members.data?.length}><SelectTrigger><SelectValue placeholder={members.data?.length ? "Choose a Member" : "No active Members available"} /></SelectTrigger><SelectContent>{members.data?.map(member => <SelectItem key={member.id} value={String(member.id)}>{member.fullName} · {member.villageWard}</SelectItem>)}</SelectContent></Select></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Amount (₹)"><Input required inputMode="decimal" value={donationAmount} onChange={event => setDonationAmount(event.target.value)} placeholder="0.00" /></Field><Field label="Payment mode"><Select value={paymentMode} onValueChange={value => setPaymentMode(value as "cash" | "cheque")}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="cash">Cash</SelectItem><SelectItem value="cheque">Cheque</SelectItem></SelectContent></Select></Field></div><Field label="Received date"><Input required type="date" value={donationDate} onChange={event => setDonationDate(event.target.value)} /></Field>{offlineDonation.error ? <p className="text-sm text-[#c94a45]">{offlineDonation.error.message}</p> : null}<Button disabled={!members.data?.length || offlineDonation.isPending} className="bg-[#28306b] text-white hover:bg-[#414a94]">{offlineDonation.isPending ? "Recording…" : "Record offline donation"}</Button></div></form>
      <form className="rounded-xl border border-[#e5dcc7] bg-[#fffdf6] p-6" onSubmit={submitExpense}><div className="flex items-start gap-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-[#fff0dc] text-[#8e6617]"><BookOpenCheck className="h-5 w-5" /></span><div><p className="section-kicker">Expense entry</p><h2 className="display-title text-2xl">Record an approved expense</h2></div></div><p className="mt-3 text-sm leading-6 text-[#746f66]">Use a public-safe description. Sensitive vendor or beneficiary notes do not belong in the public ledger field.</p><div className="mt-5 grid gap-4"><div className="grid gap-4 sm:grid-cols-2"><Field label="Amount (₹)"><Input required inputMode="decimal" value={expenseAmount} onChange={event => setExpenseAmount(event.target.value)} placeholder="0.00" /></Field><Field label="Category"><Select value={category} onValueChange={value => setCategory(value as typeof category)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="coaching">Coaching</SelectItem><SelectItem value="library">Library</SelectItem><SelectItem value="kanyadan">Kanyadan</SelectItem><SelectItem value="operations">Operations</SelectItem><SelectItem value="other">Other</SelectItem></SelectContent></Select></Field></div><Field label="Public description"><Textarea required value={description} onChange={event => setDescription(event.target.value)} placeholder="Example: Classroom notebooks and teaching materials" /></Field><Field label="Spent date"><Input required type="date" value={expenseDate} onChange={event => setExpenseDate(event.target.value)} /></Field>{expense.error ? <p className="text-sm text-[#c94a45]">{expense.error.message}</p> : null}<Button disabled={expense.isPending} className="bg-[#28306b] text-white hover:bg-[#414a94]">{expense.isPending ? "Recording…" : "Record expense"}</Button></div></form></div>
    <ProgramManager />
    <ExportControl />
    <section className="rounded-xl border border-[#e5dcc7] bg-[#fffdf6] p-6"><div className="flex items-start gap-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-[#ede7d8] text-[#28306b]"><ClipboardList className="h-5 w-5" /></span><div><p className="section-kicker">Review queue</p><h2 className="display-title text-2xl">Recent ledger records</h2></div></div><div className="mt-5 grid gap-6 lg:grid-cols-2"><div><p className="mb-3 text-sm font-bold text-[#514e48]">Donations</p>{donations.data?.length ? <div className="divide-y divide-[#e8dfcd]">{donations.data.map(row => <div key={row.id} className="flex justify-between gap-4 py-3 text-sm"><span className="truncate">{row.displayName} · {row.programName}</span><strong className="mono-number text-[#18765d]">+{inr(row.amountPaise)}</strong></div>)}</div> : <Empty text="No successful donations yet." />}</div><div><p className="mb-3 text-sm font-bold text-[#514e48]">Expenses</p>{expenses.data?.length ? <div className="divide-y divide-[#e8dfcd]">{expenses.data.map(row => <div key={row.id} className="flex justify-between gap-4 py-3 text-sm"><span className="truncate">{row.publicDescription}</span><strong className="mono-number text-[#c94a45]">−{inr(row.amountPaise)}</strong></div>)}</div> : <Empty text="No expenses yet." />}</div></div></section>
  </div>;
}

function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-[#e5dcc7] bg-[#fffdf6] p-4"><p className="section-kicker">{label}</p><p className="mono-number mt-2 text-xl text-[#28306b]">{value}</p></div>; }
function ProgramManager() { const utils = trpc.useUtils(); const programs = trpc.admin.programs.useQuery(); const [editingId, setEditingId] = useState<number | undefined>(); const [slug, setSlug] = useState(""); const [name, setName] = useState(""); const [shortDescription, setShortDescription] = useState(""); const [description, setDescription] = useState(""); const mutation = trpc.admin.saveProgram.useMutation({ onSuccess: () => { utils.admin.programs.invalidate(); setEditingId(undefined); setSlug(""); setName(""); setShortDescription(""); setDescription(""); } }); const retire = trpc.admin.retireProgram.useMutation({ onSuccess: () => utils.admin.programs.invalidate() }); return <section className="rounded-xl border border-[#e5dcc7] bg-[#fffdf6] p-6"><p className="section-kicker">Program publishing</p><h2 className="display-title mt-1 text-2xl">Create or update public program content.</h2><p className="mt-2 text-sm leading-6 text-[#746f66]">Only active programs are visible on the public site. Retiring a program preserves its existing financial references while removing it from public listings.</p><form className="mt-5 grid gap-4 lg:grid-cols-2" onSubmit={event => { event.preventDefault(); mutation.mutate({ id: editingId, slug, name, shortDescription, description, currentMetricValue: 0, isActive: true }); }}><Field label="Program name"><Input required value={name} onChange={event => setName(event.target.value)} /></Field><Field label="Public slug"><Input required value={slug} onChange={event => setSlug(event.target.value.toLowerCase().replace(/[^a-z0-9-]/g, "-"))} placeholder="community-library" /></Field><Field label="Short description" ><Input required value={shortDescription} onChange={event => setShortDescription(event.target.value)} /></Field><Field label="Public description"><Textarea required value={description} onChange={event => setDescription(event.target.value)} /></Field><div className="lg:col-span-2"><Button disabled={mutation.isPending} className="bg-[#28306b] text-white hover:bg-[#414a94]">{mutation.isPending ? "Saving…" : editingId ? "Update program" : "Publish program"}</Button></div></form><div className="mt-5 divide-y divide-[#e8dfcd]">{programs.data?.map(program => <div key={program.id} className="flex flex-wrap items-center justify-between gap-3 py-3"><div><p className="font-bold">{program.name}</p><p className="text-xs text-[#746f66]">/{program.slug} · {program.isActive ? "Public" : "Retired"}</p></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={() => { setEditingId(program.id); setSlug(program.slug); setName(program.name); setShortDescription(program.shortDescription); setDescription(program.description); }}>Edit</Button>{program.isActive ? <Button size="sm" variant="outline" className="text-[#c94a45]" onClick={() => retire.mutate({ id: program.id })}>Retire</Button> : null}</div></div>)}</div></section>; }
function ExportControl() { const [scope, setScope] = useState<"donations" | "expenses" | "both">("both"); const receipt = trpc.payments.receiptStatus.useQuery(); const exportMutation = trpc.admin.prepareFinancialExport.useMutation({ onSuccess: data => { const lines = ["record_type,date,program,display_or_description,category,amount_inr"]; data.donationRows.forEach(row => lines.push(["donation", row.donatedAt ? new Date(row.donatedAt).toISOString().slice(0, 10) : "", row.programName, row.displayName, "", (row.amountPaise / 100).toFixed(2)].map(value => `"${String(value).replaceAll('"', '""')}"`).join(","))); data.expenseRows.forEach(row => lines.push(["expense", new Date(row.spentAt).toISOString().slice(0, 10), row.programName, row.publicDescription, row.category, (row.amountPaise / 100).toFixed(2)].map(value => `"${String(value).replaceAll('"', '""')}"`).join(","))); const url = URL.createObjectURL(new Blob([lines.join("\n")], { type: "text/csv;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `gram-vikash-${scope}-ledger.csv`; anchor.click(); URL.revokeObjectURL(url); } }); return <section className="rounded-xl border border-[#e5dcc7] bg-[#fffdf6] p-6"><p className="section-kicker">Controlled export & receipts</p><h2 className="display-title mt-1 text-2xl">Prepare a minimized ledger CSV.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[#746f66]">This export contains public-safe ledger fields only. Preparing it is recorded in the audit log; it does not create a public file or expose contact details.</p><div className="mt-4 flex flex-col gap-3 sm:flex-row"><Select value={scope} onValueChange={value => setScope(value as typeof scope)}><SelectTrigger className="sm:max-w-56"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="both">Donations and expenses</SelectItem><SelectItem value="donations">Donations only</SelectItem><SelectItem value="expenses">Expenses only</SelectItem></SelectContent></Select><Button disabled={exportMutation.isPending} variant="outline" className="border-[#bfb39a] bg-[#fffdf6]" onClick={() => exportMutation.mutate({ scope })}>{exportMutation.isPending ? "Preparing…" : "Download CSV"}</Button></div><div className="mt-5 rounded-lg border border-[#e5dcc7] bg-[#fffaf0] p-4"><p className="text-sm font-bold">Receipt readiness: {receipt.data?.enabled ? "Enabled" : "Blocked"}</p><p className="mt-1 text-sm text-[#746f66]">{receipt.data?.reason ?? "Checking the payment gate…"}</p></div>{exportMutation.error ? <p className="mt-3 text-sm text-[#c94a45]">{exportMutation.error.message}</p> : null}</section>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-2"><span className="text-sm font-bold text-[#514e48]">{label}</span>{children}</label>; }
function Empty({ text }: { text: string }) { return <p className="rounded-lg border border-dashed border-[#d7cbb2] px-4 py-5 text-sm text-[#746f66]">{text}</p>; }
