import { FileLock2, Landmark, MessageSquareWarning, Vote } from "lucide-react";
import { TopNav } from "@/components/foundation/TopNav";
import { FeatureGateCard } from "@/components/foundation/FeatureGateCard";
import { trpc } from "@/lib/trpc";

export default function Governance() {
  const review = trpc.voterVerification.status.useQuery();
  const voting = trpc.voting.status.useQuery();
  const community = trpc.community.status.useQuery();
  return <div className="min-h-screen bg-[#fffdf6]"><TopNav /><main className="mx-auto max-w-5xl px-4 py-12 sm:px-6"><p className="section-kicker">Governance readiness</p><h1 className="display-title mt-2 max-w-3xl text-5xl text-[#28306b]">Trust before participation.</h1><p className="mt-4 max-w-3xl text-lg leading-8 text-[#635f58]">Community conversation, restricted voter-document review, and voting are intentionally unavailable until the foundation completes its moderation, privacy, retention, and authorized-reviewer gates.</p><div className="mt-10 grid gap-5 md:grid-cols-3"><FeatureGateCard title="Community" status={community.data?.enabled ? "Ready" : "Feature flag disabled"} description="Public community activity waits for a staffed moderation and grievance operation." /><FeatureGateCard title="Voter-document review" status={review.data?.enabled ? "Ready" : "Review gate closed"} description="Government ID documents are restricted data. No upload, review, or retention workflow is active in this release." /><FeatureGateCard title="Voting" status={voting.data?.enabled ? "Ready" : "Voting gate closed"} description="Voting remains inaccessible unless approval, verification, ballot integrity, and disclosure conditions are met." /></div><section className="ledger-panel mt-10 rounded-xl"><div className="ledger-content py-7 pr-6"><p className="section-kicker">What must happen first</p><h2 className="display-title mt-1 text-3xl">Governance cannot be a hidden switch.</h2><div className="mt-6 grid gap-4 md:grid-cols-3"><Gate icon={MessageSquareWarning} label="Moderation operation" text="Named reviewers, escalation policy, and grievance handling need to be active." /><Gate icon={FileLock2} label="Restricted data controls" text="Private storage, access records, retention, and deletion policy need formal approval." /><Gate icon={Vote} label="Voting safeguards" text="Eligibility, one-vote enforcement, public result rules, and decision ownership need approval." /></div></div></section></main></div>;
}

function Gate({ icon: Icon, label, text }: { icon: typeof Landmark; label: string; text: string }) { return <div className="rounded-lg border border-[#e5dcc7] bg-[#fffaf0] p-4"><Icon className="h-5 w-5 text-[#c94a45]" /><h3 className="mt-3 font-bold">{label}</h3><p className="mt-1 text-sm leading-6 text-[#635f58]">{text}</p></div>; }
