import { FileCheck2, LockKeyhole, ShieldCheck, WalletCards } from "lucide-react";
import { Link } from "wouter";
import { TopNav } from "@/components/foundation/TopNav";

const commitments = [
  { icon: WalletCards, title: "Derived financial totals", text: "Public totals are calculated from successful donation and recorded expense entries, rather than from manually maintained counters." },
  { icon: LockKeyhole, title: "Privacy by projection", text: "A Member’s anonymity setting controls public donor-wall display only. Internal financial records remain attributable for accounting and audit." },
  { icon: ShieldCheck, title: "Capability gates", text: "Live payments, community interaction, voter-document review, and voting remain disabled until their documented operational and approval requirements are met." },
  { icon: FileCheck2, title: "Auditable operations", text: "Protected administrator actions create audit evidence. Public views intentionally omit contact details, private notes, and restricted documents." },
];

export default function Trust() { return <div className="min-h-screen bg-[#fffdf6]"><TopNav /><main className="mx-auto max-w-5xl px-4 py-12 sm:px-6"><p className="section-kicker">Trust & accountability</p><h1 className="display-title mt-2 max-w-3xl text-5xl text-[#28306b]">Transparency is a practice, not a promise card.</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-[#635f58]">Gram Vikash Foundation is building a public record that explains what is visible, what remains private, and which capabilities have not yet been approved for use.</p><section className="mt-10 grid gap-5 md:grid-cols-2">{commitments.map(item => <article key={item.title} className="rounded-xl border border-[#e5dcc7] bg-[#fffdf6] p-6 shadow-[0_10px_24px_rgba(34,35,77,0.05)]"><item.icon className="h-6 w-6 text-[#c94a45]" /><h2 className="display-title mt-4 text-2xl">{item.title}</h2><p className="mt-2 leading-7 text-[#635f58]">{item.text}</p></article>)}</section><section className="ledger-panel mt-10 rounded-xl"><div className="ledger-content py-7 pr-6"><p className="section-kicker">Current status</p><h2 className="display-title mt-1 text-3xl">What is available now.</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><div><h3 className="font-bold">Available</h3><p className="mt-1 text-sm leading-6 text-[#635f58]">Public transparency views, Member profile management, protected offline ledger operations, and public-safe program publishing.</p></div><div><h3 className="font-bold">Not enabled</h3><p className="mt-1 text-sm leading-6 text-[#635f58]">Live Razorpay payments, automated receipts, community posting/chat, voter-document review, and voting.</p></div></div><p className="mt-6 text-sm text-[#746f66]">This page is operational information, not legal, tax, or compliance advice. The foundation must obtain qualified review before activating regulated or sensitive capabilities.</p><Link href="/transparency" className="soft-focus mt-5 inline-flex rounded-md bg-[#28306b] px-4 py-2.5 font-bold text-white no-underline">Inspect the ledger</Link></div></section></main></div>; }
