"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
type Program = { id: number; name: string; slug: string; shortDescription: string; isActive: boolean };

export default function ProgramManager({ programs }: { programs: Program[] }) {
  const router = useRouter(); const [status, setStatus] = useState<{ tone: "success" | "error"; message: string } | null>(null); const [saving, setSaving] = useState(false); const [retiringId, setRetiringId] = useState<number | null>(null);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (saving) return; const form = event.currentTarget; const fd = new FormData(form); const slug = String(fd.get("slug") ?? "").trim(); if (!/^[a-z0-9-]+$/.test(slug)) { setStatus({ tone: "error", message: "Use lowercase letters, numbers, and hyphens only for the URL slug." }); return; } setSaving(true); setStatus(null); try { const payload = { slug, name: fd.get("name"), shortDescription: fd.get("shortDescription"), description: fd.get("description"), targetMetric: fd.get("targetMetric"), currentMetricValue: Number(fd.get("currentMetricValue") || 0), isActive: fd.get("isActive") === "on" }; const res = await fetch("/api/admin/programs", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); if (!res.ok) throw new Error(); form.reset(); setStatus({ tone: "success", message: "Program saved with audit evidence. The list is refreshing." }); router.refresh(); } catch { setStatus({ tone: "error", message: "Program could not be saved. Review the required fields and your admin session." }); } finally { setSaving(false); } }
  async function retire(id: number) { if (retiringId !== null) return; setRetiringId(id); setStatus(null); try { const res = await fetch(`/api/admin/programs/${id}`, { method: "DELETE" }); if (!res.ok) throw new Error(); setStatus({ tone: "success", message: "Program retired with audit evidence. The public record has been refreshed." }); router.refresh(); } catch { setStatus({ tone: "error", message: "Program could not be retired. Please try again once." }); } finally { setRetiringId(null); } }
  return <div className="program-manager"><form className="ledger operation-form" onSubmit={create}><div className="form-heading"><div><p className="eyebrow">Public content</p><h2>Publish a program</h2></div><span className="stamp">AUDITED</span></div><p>Publish only approved, consent-cleared information. Metric values must be supported by the program record.</p><label>Name<input name="name" required disabled={saving} /></label><label>URL slug<input name="slug" placeholder="community-library" required disabled={saving} /></label><label>Short description<input name="shortDescription" required disabled={saving} /></label><label>Full description<textarea name="description" required disabled={saving} /></label><label>Target metric<input name="targetMetric" placeholder="Books available" disabled={saving} /></label><label>Current value<input name="currentMetricValue" type="number" min="0" defaultValue="0" required disabled={saving} /></label><label className="check-row"><input name="isActive" type="checkbox" defaultChecked disabled={saving} />Publish publicly</label><button type="submit" className="button" disabled={saving}>{saving ? "Saving program…" : "Save program"}</button>{status ? <p className={`form-status ${status.tone}`} role="status">{status.message}</p> : null}</form><section className="ledger program-list"><div className="form-heading"><div><p className="eyebrow">Current register</p><h2>Existing programs</h2></div><span className="stamp">{programs.length} RECORDS</span></div>{programs.length ? programs.map(program => <div key={program.id} className="program-list-row"><div><strong>{program.name}</strong><p>/{program.slug} · {program.isActive ? "Public" : "Retired"}</p></div>{program.isActive ? <button onClick={() => void retire(program.id)} type="button" disabled={retiringId !== null}>{retiringId === program.id ? "Retiring…" : "Retire"}</button> : <span className="stamp">RETIRED</span>}</div>) : <div className="empty-inline"><strong>No programs are recorded yet.</strong><p>Approved program records created here will be available for controlled public publication.</p></div>}</section></div>;
}
