import Link from "next/link";
import { getFeatureGates, getMemberByUserId, getMemberDonationHistory } from "@/server/db";
import { requireManagedUser } from "@/lib/auth/session";
import ProfileForm from "./profile-form";

const inr = (paise: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(paise / 100);

export default async function MyDonationsPage() {
  const user = await requireManagedUser();
  const [member, history, gates] = await Promise.all([getMemberByUserId(user.id), getMemberDonationHistory(user.id), getFeatureGates()]);
  return <main className="dashboard-page"><header className="dashboard-heading"><p className="eyebrow">Member dashboard</p><h1>Your record, under your control.</h1><p>Update your profile, decide how your name appears publicly, and review the donation history linked to your registered Member record.</p></header><section className="member-snapshot">{member ? <><article><span>Member record</span><strong>{member.fullName}</strong><p>{member.villageWard}</p></article><article><span>Public display</span><strong>{member.isAnonymous ? "Anonymous" : "Visible with consent"}</strong><p>Anonymity changes the public display only.</p></article><article><span>Donation entries</span><strong>{history.length}</strong><p>Financial records remain internally linked.</p></article></> : <article className="member-snapshot-wide"><span>Profile completion required</span><strong>Finish your Member record before using registered services.</strong><p>Your personal data stays out of public ledgers; only your chosen display preference affects public recognition.</p></article>}</section><section className="dashboard-grid"><article className="dashboard-card"><div className="card-title"><div><p className="eyebrow">Donation history</p><h2>Recorded support</h2></div><Link href="/donate">Donation status →</Link></div>{history.length ? <div className="history-list">{history.map(row => <div key={row.id}><strong>{inr(row.amountPaise)}</strong><span>{row.programName} · {row.status} · {new Date(row.donatedAt).toLocaleDateString()}</span></div>)}</div> : <div className="empty-inline"><strong>No donation records yet.</strong><p>Online checkout stays unavailable until the payment approval gate is complete. Offline entries, if any, appear here after an administrator records them.</p></div>}</article><article className="dashboard-card receipt-card"><p className="eyebrow">Receipt readiness</p><h2>{gates.payments_live ? "Receipt event mapping pending" : "Receipts are not active"}</h2><p>{gates.payments_live ? "Receipt events have not yet been activated." : "Receipts become available only after payment verification, reconciliation ownership, finance review, and approval are complete."}</p><span className="stamp">APPROVAL GATED</span></article></section><section className="profile-panel"><div><p className="eyebrow">Profile & display preferences</p><h2>Keep your record accurate.</h2><p>Contact and village/ward details support internal administration. Your donor-wall preference applies only to the public display.</p></div><ProfileForm initial={member ?? { email: user.email, fullName: user.name }} /></section></main>;
}
