"use client";

import { FormEvent, useState } from "react";

type Profile = { fullName?: string | null; phone?: string | null; email?: string | null; dateOfBirth?: string | null; villageWard?: string | null; publicDisplayName?: string | null; isAnonymous?: boolean | null };
export default function ProfileForm({ initial }: { initial: Profile }) {
  const [status, setStatus] = useState<string>("");
  const [saving, setSaving] = useState(false);
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setStatus(""); const data = new FormData(event.currentTarget); const response = await fetch("/api/members/me", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ fullName: data.get("fullName"), phone: data.get("phone"), email: data.get("email"), dateOfBirth: data.get("dateOfBirth"), villageWard: data.get("villageWard"), publicDisplayName: data.get("publicDisplayName"), isAnonymous: data.get("isAnonymous") === "on" }) }); setSaving(false); setStatus(response.ok ? "Profile saved. Your public-display choice has been updated." : "Profile could not be saved. Please check the required fields."); }
  return <form onSubmit={save} className="ledger" style={{ display: "grid", gap: 14 }}><h2>{initial.fullName ? "Update your Member profile" : "Complete your Member profile"}</h2><label>Full name<input name="fullName" defaultValue={initial.fullName ?? ""} required /></label><label>Phone number<input name="phone" defaultValue={initial.phone ?? ""} required /></label><label>Email<input name="email" type="email" defaultValue={initial.email ?? ""} /></label><label>Date of birth<input name="dateOfBirth" type="date" defaultValue={initial.dateOfBirth ?? ""} required /></label><label>Village / ward<input name="villageWard" defaultValue={initial.villageWard ?? ""} required /></label><label>Public display name<input name="publicDisplayName" defaultValue={initial.publicDisplayName ?? ""} placeholder="Optional" /></label><label style={{ display: "flex", gap: 8, alignItems: "center" }}><input name="isAnonymous" type="checkbox" defaultChecked={initial.isAnonymous ?? true} /> Keep my public donor display anonymous</label><button className="button" type="submit" disabled={saving}>{saving ? "Saving…" : "Save profile"}</button>{status ? <p aria-live="polite">{status}</p> : null}</form>;
}
